-- UGG catalog seed (search / brands). Real StockX imagery: run `npm run kicks:import` with KicksDB.

insert into public.catalog_products (
  handle,
  title,
  brand,
  description,
  department_slug,
  tags,
  product_type,
  home_rails,
  activities,
  variant_size_preset,
  featured_image_url,
  image_gallery,
  price_min,
  price_max,
  currency,
  trend_score,
  category,
  gender,
  source_url,
  published
)
values
  (
    'ugg-tasman-chestnut',
    'UGG Tasman — Chestnut',
    'UGG',
    'Heritage slipper with suede upper and plush UGGplush lining.',
    'women',
    array['dept-women', 'sneakers', 'slipper', 'ugg', 'home-trending-sneakers', 'activity-training'],
    'sneaker',
    array['trending-sneakers', 'popular-local', 'new-at-exch'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=900&q=85',
    array['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1200&q=85'],
    98, 130, 'USD', 88, 'slippers', 'women',
    null,
    true
  ),
  (
    'ugg-tazz-gazette',
    'UGG Tazz — Gazette',
    'UGG',
    'Platform slipper with bold UGG branding and soft interior.',
    'women',
    array['dept-women', 'sneakers', 'slipper', 'ugg', 'home-trending-sneakers', 'activity-training'],
    'sneaker',
    array['trending-sneakers', 'popular-local'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1603487742131-4160f58f43b7?w=900&q=85',
    array['https://images.unsplash.com/photo-1603487742131-4160f58f43b7?w=1200&q=85'],
    110, 145, 'USD', 86, 'slippers', 'women',
    null,
    true
  ),
  (
    'ugg-classic-mini-ii-black',
    'UGG Classic Mini II — Black',
    'UGG',
    'Ankle-height Classic silhouette with water-resistant suede.',
    'women',
    array['dept-women', 'dept-men', 'sneakers', 'boot', 'ugg', 'home-trending-sneakers'],
    'sneaker',
    array['trending-sneakers', 'popular-local', 'below-retail'],
    array['training', 'running'],
    'shoe',
    'https://images.unsplash.com/photo-1608256246200-53e635bfc0f1?w=900&q=85',
    array['https://images.unsplash.com/photo-1608256246200-53e635bfc0f1?w=1200&q=85'],
    140, 185, 'USD', 84, 'boots', 'women',
    null,
    true
  ),
  (
    'ugg-neumel-chocolate',
    'UGG Neumel — Chocolate',
    'UGG',
    'Chukka-inspired boot with wool lining for everyday wear.',
    'men',
    array['dept-men', 'sneakers', 'boot', 'ugg', 'home-trending-sneakers', 'activity-training'],
    'sneaker',
    array['trending-sneakers', 'popular-local'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=900&q=85',
    array['https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=1200&q=85'],
    155, 210, 'USD', 82, 'boots', 'men',
    null,
    true
  )
on conflict (handle) do update
set
  title = excluded.title,
  brand = excluded.brand,
  description = excluded.description,
  department_slug = excluded.department_slug,
  tags = excluded.tags,
  product_type = excluded.product_type,
  home_rails = excluded.home_rails,
  activities = excluded.activities,
  variant_size_preset = excluded.variant_size_preset,
  featured_image_url = excluded.featured_image_url,
  image_gallery = excluded.image_gallery,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  currency = excluded.currency,
  trend_score = excluded.trend_score,
  category = excluded.category,
  gender = excluded.gender,
  source_url = excluded.source_url,
  published = excluded.published,
  updated_at = now();
