-- Puffer / down outerwear (source: data/puffer-outerwear-catalog.json, npm run seed:puffer)

insert into public.catalog_products (
  handle, title, brand, description, department_slug, tags, product_type,
  home_rails, activities, variant_size_preset, featured_image_url, image_gallery,
  price_min, price_max, currency, trend_score, category, gender, source_url, published
)
values
  (
    'the-north-face-1996-retro-nuptse-black',
    'The North Face 1996 Retro Nuptse Jacket — Black',
    'The North Face',
    'Classic boxy baffled down jacket with DWR-treated ripstop, packable hood, and signature oversized baffles.',
    'unisex',
    array['dept-men','dept-women','apparel','jacket','puffer','down-jacket','outerwear','north-face','home-featured-apparel'],
    'apparel',
    array['featured-apparel','popular-local','new-at-exch'],
    array['training','running'],
    'apparel',
    'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=900&q=85',
    array['https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=900&q=85'],
    280, 340, 'USD', 96,
    'puffer-jackets', 'unisex',
    null,
    true
  ),
  (
    'the-north-face-himalayan-parka-tnf-black',
    'The North Face Himalayan Parka — TNF Black',
    'The North Face',
    'Heavyweight expedition-style down parka with detachable faux-fur hood ruff and abrasion panels.',
    'men',
    array['dept-men','apparel','jacket','parka','puffer','down-jacket','outerwear','north-face','home-featured-apparel'],
    'apparel',
    array['featured-apparel','popular-local'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=900&q=85',
    array['https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=900&q=85'],
    350, 480, 'USD', 94,
    'parkas', 'men',
    null,
    true
  ),
  (
    'the-north-face-mcmurdo-parka-vanadis-grey',
    'The North Face McMurdo Parka — Vanadis Grey',
    'The North Face',
    'Waterproof breathable shell with RDS down fill, storm cuffs, and multiple zip pockets.',
    'men',
    array['dept-men','apparel','jacket','parka','puffer','outerwear','north-face','home-featured-apparel'],
    'apparel',
    array['featured-apparel','below-retail'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=900&q=85',
    array['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=900&q=85'],
    320, 420, 'USD', 92,
    'parkas', 'men',
    null,
    true
  ),
  (
    'moncler-maya-short-down-jacket-black',
    'Moncler Maya Short Down Jacket — Black',
    'Moncler',
    'Gloss nylon laqué with signature felt logo patch, detachable hood option (season-dependent), RDS down insulation.',
    'unisex',
    array['dept-men','dept-women','apparel','jacket','puffer','down-jacket','outerwear','moncler','home-featured-apparel'],
    'apparel',
    array['featured-apparel','popular-local','new-at-exch'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1539533018447-63fcce2678e2?w=900&q=85',
    array['https://images.unsplash.com/photo-1539533018447-63fcce2678e2?w=900&q=85'],
    1100, 1450, 'USD', 98,
    'puffer-jackets', 'unisex',
    null,
    true
  ),
  (
    'moncler-montbeliard-long-puffer-black',
    'Moncler Montbeliard Long Down Jacket — Black',
    'Moncler',
    'Long baffled silhouette with detachable hood and two-way zipper for city layering.',
    'men',
    array['dept-men','apparel','jacket','puffer','down-jacket','outerwear','moncler','home-featured-apparel'],
    'apparel',
    array['featured-apparel','popular-local'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd4?w=900&q=85',
    array['https://images.unsplash.com/photo-1551488831-00ddcb6c6bd4?w=900&q=85'],
    1280, 1720, 'USD', 96,
    'puffer-jackets', 'men',
    null,
    true
  ),
  (
    'moncler-frgmt-bamboo-puffer-black',
    'Moncler × FRGMT Bamboo Puffer — Black',
    'Moncler',
    'Collaboration-weight short puffer with contrast lining and tonal branding.',
    'unisex',
    array['dept-men','dept-women','apparel','jacket','puffer','outerwear','moncler','home-featured-apparel'],
    'apparel',
    array['featured-apparel','new-at-exch'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1617127365659-c47fa863d238?w=900&q=85',
    array['https://images.unsplash.com/photo-1617127365659-c47fa863d238?w=900&q=85'],
    1350, 1850, 'USD', 95,
    'puffer-jackets', 'unisex',
    null,
    true
  ),
  (
    'canada-goose-expedition-parka-black-red',
    'Canada Goose Expedition Parka — Black',
    'Canada Goose',
    'Arctic-tested parka with coyote fur ruff option, fleece-lined pockets, and 625-fill power duck down.',
    'unisex',
    array['dept-men','dept-women','apparel','jacket','parka','puffer','outerwear','canada-goose','home-featured-apparel'],
    'apparel',
    array['featured-apparel','popular-local'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&q=85',
    array['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&q=85'],
    1450, 1600, 'USD', 97,
    'parkas', 'unisex',
    null,
    true
  ),
  (
    'canada-goose-chilliwack-bomber-blue',
    'Canada Goose Chilliwack Bomber — Navy',
    'Canada Goose',
    'Short flight jacket length with ribbed waist, heavy Arctic Tech shell, and down fill.',
    'men',
    array['dept-men','apparel','jacket','bomber','puffer','outerwear','canada-goose','home-featured-apparel'],
    'apparel',
    array['featured-apparel'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&q=85',
    array['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&q=85'],
    995, 1200, 'USD', 93,
    'bombers', 'men',
    null,
    true
  ),
  (
    'stone-island-crinkle-reps-ny-down-olive',
    'Stone Island Crinkle Reps NY Down Jacket — Olive',
    'Stone Island',
    'Resin-coated nylon reps with detachable compass badge and medium-weight down fill.',
    'men',
    array['dept-men','apparel','jacket','puffer','outerwear','stone-island','home-featured-apparel'],
    'apparel',
    array['featured-apparel','popular-local'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=900&q=85',
    array['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=900&q=85'],
    820, 1100, 'USD', 94,
    'puffer-jackets', 'men',
    null,
    true
  ),
  (
    'patagonia-down-sweater-hoody-black',
    'Patagonia Down Sweater Hoody — Black',
    'Patagonia',
    'Lightweight 800-fill RDS down hoodie that stuffs into its own pocket; ideal mid-layer.',
    'unisex',
    array['dept-men','dept-women','apparel','jacket','puffer','down-jacket','outerwear','patagonia','home-featured-apparel'],
    'apparel',
    array['featured-apparel','below-retail'],
    array['training','running'],
    'apparel',
    'https://images.unsplash.com/photo-1620799139504-3c7469992d73?w=900&q=85',
    array['https://images.unsplash.com/photo-1620799139504-3c7469992d73?w=900&q=85'],
    280, 330, 'USD', 90,
    'puffer-jackets', 'unisex',
    null,
    true
  ),
  (
    'arcteryx-thorium-hoody-black',
    'Arc''teryx Thorium Hoody — Black',
    'Arc''teryx',
    'Coreloft synthetic in moisture zones blended with lofty down chambers; trim alpine fit.',
    'unisex',
    array['dept-men','dept-women','apparel','jacket','puffer','down-jacket','outerwear','arc-teryx','home-featured-apparel'],
    'apparel',
    array['featured-apparel','popular-local'],
    array['training','running'],
    'apparel',
    'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=900&q=85',
    array['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=900&q=85'],
    400, 480, 'USD', 91,
    'puffer-jackets', 'unisex',
    null,
    true
  ),
  (
    'columbia-pike-lake-ii-hooded-puffer-grey',
    'Columbia Pike Lake II Hooded Jacket — City Grey',
    'Columbia',
    'Thermarator synthetic insulation with Omni-Heat reflective lining — warm without premium down pricing.',
    'men',
    array['dept-men','apparel','jacket','puffer','outerwear','columbia','home-featured-apparel'],
    'apparel',
    array['featured-apparel','below-retail'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1516762689617-e1cffcef938d?w=900&q=85',
    array['https://images.unsplash.com/photo-1516762689617-e1cffcef938d?w=900&q=85'],
    120, 160, 'USD', 87,
    'puffer-jackets', 'men',
    null,
    true
  )
on conflict (handle) do update set
  title = excluded.title,
  brand = excluded.brand,
  description = excluded.description,
  department_slug = excluded.department_slug,
  tags = excluded.tags,
  product_type = excluded.product_type,
  home_rails = excluded.home_rails,
  activities = excluded.activities,
  variant_size_preset = excluded.variant_size_preset,
  featured_image_url = excluded.featured_image_url,
  image_gallery = excluded.image_gallery,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  currency = excluded.currency,
  trend_score = excluded.trend_score,
  category = excluded.category,
  gender = excluded.gender,
  source_url = excluded.source_url,
  published = excluded.published,
  updated_at = now();
