-- Avant-garde / designer catalog (source: data/designer-catalog.json, npm run seed:designer)

insert into public.catalog_products (
  handle, title, brand, description, department_slug, tags, product_type,
  home_rails, activities, variant_size_preset, featured_image_url, image_gallery,
  price_min, price_max, currency, trend_score, category, gender, source_url, published
)
values
  (
    'rick-owens-geobasket-dust',
    'Rick Owens Geobasket — Dust',
    'Rick Owens',
    'Sculptural high-top with exaggerated tongue and grained leather upper.',
    'men',
    array['dept-men','dept-women','sneakers','designer','avant-garde','rick-owens','home-featured-designer'],
    'sneaker',
    array['featured-designer','trending-sneakers','new-at-exch'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&q=85',
    array['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&q=85'],
    820, 1450, 'USD', 96,
    'sneakers', 'unisex',
    null,
    true
  ),
  (
    'rick-owens-drkshdw-ramones-milk',
    'Rick Owens DRKSHDW Ramones Low — Milk',
    'Rick Owens',
    'Low-profile DRKSHDW sneaker with elongated toe and tonal laces.',
    'unisex',
    array['dept-men','dept-women','sneakers','designer','avant-garde','rick-owens','home-featured-designer'],
    'sneaker',
    array['featured-designer','popular-local'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1489987707025-afad1a0f5ac4?w=900&q=85',
    array['https://images.unsplash.com/photo-1489987707025-afad1a0f5ac4?w=900&q=85'],
    420, 620, 'USD', 94,
    'sneakers', 'unisex',
    null,
    true
  ),
  (
    'rick-owens-cargo-pod-shorts-black',
    'Rick Owens Cargo Pod Shorts — Black',
    'Rick Owens',
    'Dropped-crotch cargo shorts in heavy cotton with drawcord hem.',
    'men',
    array['dept-men','apparel','shorts','designer','avant-garde','rick-owens','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=900&q=85',
    array['https://images.unsplash.com/photo-1617137968427-85924c800a22?w=900&q=85'],
    380, 520, 'USD', 91,
    'shorts', 'men',
    null,
    true
  ),
  (
    'boris-bidjan-saberi-leather-jacket-black',
    'Boris Bidjan Saberi Bias Cut Leather Jacket — Black',
    'Boris Bidjan Saberi',
    'Hand-finished lambskin with asymmetric zip and anatomical paneling.',
    'men',
    array['dept-men','apparel','jacket','leather','designer','avant-garde','bbs','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel','new-at-exch'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&q=85',
    array['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&q=85'],
    2800, 4200, 'USD', 95,
    'jackets', 'men',
    null,
    true
  ),
  (
    'boris-bidjan-saberi-panel-sneaker-11',
    'Boris Bidjan Saberi Panel Sneaker 11 — White',
    'Boris Bidjan Saberi',
    'Deconstructed low-top with wrapped panels and distressed cup sole.',
    'unisex',
    array['dept-men','dept-women','sneakers','designer','avant-garde','bbs','home-featured-designer'],
    'sneaker',
    array['featured-designer','trending-sneakers'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1594938353580-b54fbaa52279?w=900&q=85',
    array['https://images.unsplash.com/photo-1594938353580-b54fbaa52279?w=900&q=85'],
    680, 980, 'USD', 93,
    'sneakers', 'unisex',
    null,
    true
  ),
  (
    'boris-bidjan-saberi-wrapped-cargo-asphalt',
    'Boris Bidjan Saberi Wrapped Cargo Pant — Asphalt',
    'Boris Bidjan Saberi',
    'Articulated cargo trouser with spiral leg seam and waxed cotton.',
    'men',
    array['dept-men','apparel','pants','designer','avant-garde','bbs','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=900&q=85',
    array['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=900&q=85'],
    720, 1100, 'USD', 90,
    'pants', 'men',
    null,
    true
  ),
  (
    'ann-demeulemeester-back-lace-blazer',
    'Ann Demeulemeester Back-Lace Blazer — Black',
    'Ann Demeulemeester',
    'Tailored wool blazer with signature rear lacing and slim lapel.',
    'women',
    array['dept-women','dept-men','apparel','blazer','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel','new-at-exch'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1539533018447-63fcce2678e2?w=900&q=85',
    array['https://images.unsplash.com/photo-1539533018447-63fcce2678e2?w=900&q=85'],
    1100, 1650, 'USD', 94,
    'blazers', 'women',
    null,
    true
  ),
  (
    'ann-demeulemeester-front-zip-boot',
    'Ann Demeulemeester Front-Zip Leather Boot — Black',
    'Ann Demeulemeester',
    'Ankle boot with front zip, stacked heel, and brushed calfskin.',
    'unisex',
    array['dept-women','dept-men','sneakers','boot','designer','avant-garde','home-featured-designer'],
    'sneaker',
    array['featured-designer','trending-sneakers'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=900&q=85',
    array['https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=900&q=85'],
    890, 1280, 'USD', 92,
    'boots', 'unisex',
    null,
    true
  ),
  (
    'ann-demeulemeester-wide-wool-trouser',
    'Ann Demeulemeester Wool Wide Trouser — Charcoal',
    'Ann Demeulemeester',
    'High-rise wide leg in brushed wool with pressed crease.',
    'women',
    array['dept-women','apparel','pants','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1503342217505-984ad4ec80ab?w=900&q=85',
    array['https://images.unsplash.com/photo-1503342217505-984ad4ec80ab?w=900&q=85'],
    520, 780, 'USD', 89,
    'pants', 'women',
    null,
    true
  ),
  (
    'maison-margiela-replica-sneaker-white',
    'Maison Margiela Replica Sneaker — White / Grey Tab',
    'Maison Margiela',
    'German army trainer-inspired low with hand-painted finish and numbered tab.',
    'unisex',
    array['dept-men','dept-women','sneakers','designer','avant-garde','margiela','home-featured-designer'],
    'sneaker',
    array['featured-designer','trending-sneakers','popular-local'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=900&q=85',
    array['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=900&q=85'],
    420, 650, 'USD', 97,
    'sneakers', 'unisex',
    null,
    true
  ),
  (
    'maison-margiela-tabi-ballerina-black',
    'Maison Margiela Tabi Ballerina — Black',
    'Maison Margiela',
    'Split-toe leather flat with cleft vamp and minimal heel.',
    'women',
    array['dept-women','sneakers','designer','avant-garde','margiela','home-featured-designer'],
    'sneaker',
    array['featured-designer','new-at-exch'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=900&q=85',
    array['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=900&q=85'],
    680, 920, 'USD', 95,
    'flats', 'women',
    null,
    true
  ),
  (
    'maison-margiela-split-toe-oxford',
    'Maison Margiela Split-Toe Oxford — Black',
    'Maison Margiela',
    'Polished calfskin oxford with iconic cleft toe and leather sole.',
    'men',
    array['dept-men','sneakers','designer','avant-garde','margiela','home-featured-designer'],
    'sneaker',
    array['featured-designer','trending-sneakers'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=900&q=85',
    array['https://images.unsplash.com/photo-1617137968427-85924c800a22?w=900&q=85'],
    750, 1050, 'USD', 93,
    'dress-shoes', 'men',
    null,
    true
  ),
  (
    'guidi-pl2-front-zip-boot-black',
    'Guidi PL2 Front Zip Boot — Black Horse Leather',
    'Guidi',
    'Front-zip ankle boot in vegetable-tanned horse leather with Goodyear welt.',
    'unisex',
    array['dept-men','dept-women','sneakers','boot','designer','avant-garde','guidi','home-featured-designer'],
    'sneaker',
    array['featured-designer','trending-sneakers','new-at-exch'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1608256246200-53e635bfc0f1?w=900&q=85',
    array['https://images.unsplash.com/photo-1608256246200-53e635bfc0f1?w=900&q=85'],
    1280, 1850, 'USD', 96,
    'boots', 'unisex',
    null,
    true
  ),
  (
    'guidi-788z-back-zip-wine',
    'Guidi 788Z Back Zip Boot — Wine',
    'Guidi',
    'Mid-height back-zip boot with object-dyed horse leather and stacked heel.',
    'unisex',
    array['dept-men','dept-women','sneakers','boot','designer','avant-garde','guidi','home-featured-designer'],
    'sneaker',
    array['featured-designer','popular-local'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=900&q=85',
    array['https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=900&q=85'],
    1450, 2100, 'USD', 94,
    'boots', 'unisex',
    null,
    true
  ),
  (
    'guidi-920-derby-black',
    'Guidi 920 Derby — Black',
    'Guidi',
    'Classic derby on leather sole with Guidi’s signature deep dye finish.',
    'men',
    array['dept-men','sneakers','designer','avant-garde','guidi','home-featured-designer'],
    'sneaker',
    array['featured-designer','trending-sneakers'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&q=85',
    array['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&q=85'],
    980, 1400, 'USD', 92,
    'dress-shoes', 'men',
    null,
    true
  ),
  (
    'comme-des-garcons-play-heart-tee',
    'Comme des Garçons PLAY Heart Logo Tee — White',
    'Comme des Garçons',
    'Cotton jersey tee with embroidered heart logo at chest.',
    'unisex',
    array['dept-men','dept-women','apparel','tee','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel','popular-local'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1622445275463-87121a938818?w=900&q=85',
    array['https://images.unsplash.com/photo-1622445275463-87121a938818?w=900&q=85'],
    95, 140, 'USD', 90,
    'tees', 'unisex',
    null,
    true
  ),
  (
    'yohji-yamamoto-wide-pleat-pant',
    'Yohji Yamamoto Wide Pleat Trouser — Black',
    'Yohji Yamamoto',
    'Draped wool trouser with deep pleats and cropped break.',
    'men',
    array['dept-men','apparel','pants','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=900&q=85',
    array['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=900&q=85'],
    620, 890, 'USD', 91,
    'pants', 'men',
    null,
    true
  ),
  (
    'raf-simons-replicant-runner',
    'Raf Simons Replicant Runner — Silver',
    'Raf Simons',
    'Futurist runner with translucent panels and oversized cage.',
    'unisex',
    array['dept-men','dept-women','sneakers','designer','avant-garde','home-featured-designer'],
    'sneaker',
    array['featured-designer','trending-sneakers'],
    array['running','training'],
    'shoe',
    'https://images.unsplash.com/photo-1489987707025-afad1a0f5ac4?w=900&q=85',
    array['https://images.unsplash.com/photo-1489987707025-afad1a0f5ac4?w=900&q=85'],
    380, 720, 'USD', 88,
    'sneakers', 'unisex',
    null,
    true
  ),
  (
    'julius-bonded-scarab-jacket',
    'Julius Bonded Scarab Jacket — Black',
    'Julius',
    'Technical bonded shell with articulated sleeves and matte hardware.',
    'men',
    array['dept-men','apparel','jacket','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&q=85',
    array['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&q=85'],
    980, 1400, 'USD', 89,
    'jackets', 'men',
    null,
    true
  ),
  (
    'dries-van-noten-floral-silk-shirt',
    'Dries Van Noten Floral Silk Shirt — Navy',
    'Dries Van Noten',
    'Relaxed camp-collar shirt in printed silk with mother-of-pearl buttons.',
    'men',
    array['dept-men','apparel','shirt','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel','new-at-exch'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1594938353580-b54fbaa52279?w=900&q=85',
    array['https://images.unsplash.com/photo-1594938353580-b54fbaa52279?w=900&q=85'],
    520, 720, 'USD', 87,
    'shirts', 'men',
    null,
    true
  ),
  (
    'haider-ackermann-silk-wrap-blouse',
    'Haider Ackermann Silk Wrap Blouse — Ink',
    'Haider Ackermann',
    'Fluid silk blouse with asymmetric wrap and elongated cuff.',
    'women',
    array['dept-women','apparel','top','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1503342217505-984ad4ec80ab?w=900&q=85',
    array['https://images.unsplash.com/photo-1503342217505-984ad4ec80ab?w=900&q=85'],
    780, 1150, 'USD', 88,
    'tops', 'women',
    null,
    true
  ),
  (
    'undercover-68-scab-denim',
    'Undercover 68 Scab Denim — Indigo',
    'Undercover',
    'Straight denim with distressed scab graphics and vintage wash.',
    'unisex',
    array['dept-men','dept-women','apparel','denim','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel','popular-local'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1542272604-787c3835535d?w=900&q=85',
    array['https://images.unsplash.com/photo-1542272604-787c3835535d?w=900&q=85'],
    420, 680, 'USD', 90,
    'denim', 'unisex',
    null,
    true
  ),
  (
    'junya-watanabe-denim-trucker',
    'Junya Watanabe Denim Trucker — Washed Blue',
    'Junya Watanabe',
    'Hybrid trucker with patchwork denim panels and contrast stitching.',
    'men',
    array['dept-men','apparel','jacket','denim','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel'],
    array['training'],
    'apparel',
    'https://images.unsplash.com/photo-1539533018447-63fcce2678e2?w=900&q=85',
    array['https://images.unsplash.com/photo-1539533018447-63fcce2678e2?w=900&q=85'],
    680, 980, 'USD', 86,
    'jackets', 'men',
    null,
    true
  ),
  (
    'acronym-j1a-gt-jacket',
    'Acronym J1A-GT Jacket — Black',
    'Acronym',
    'Technical shell with articulated fit, storm flap, and taped seams.',
    'men',
    array['dept-men','apparel','jacket','techwear','designer','avant-garde','home-featured-designer'],
    'apparel',
    array['featured-designer','featured-apparel','new-at-exch'],
    array['training','running'],
    'apparel',
    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&q=85',
    array['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&q=85'],
    1100, 1650, 'USD', 92,
    'jackets', 'men',
    null,
    true
  ),
  (
    'visvim-fbt-bearfoot-moc',
    'Visvim FBT Bearfoot Moc — Sand',
    'Visvim',
    'Fringed moccasin with Vibram sole and hand-stitched upper.',
    'men',
    array['dept-men','sneakers','designer','avant-garde','home-featured-designer'],
    'sneaker',
    array['featured-designer','trending-sneakers'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1603487742131-4160f58f43b7?w=900&q=85',
    array['https://images.unsplash.com/photo-1603487742131-4160f58f43b7?w=900&q=85'],
    680, 920, 'USD', 87,
    'moccasins', 'men',
    null,
    true
  ),
  (
    'common-projects-achilles-low',
    'Common Projects Achilles Low — White',
    'Common Projects',
    'Minimal Italian leather sneaker with gold serial stamp at heel.',
    'unisex',
    array['dept-men','dept-women','sneakers','designer','minimal','home-featured-designer'],
    'sneaker',
    array['featured-designer','popular-local'],
    array['training'],
    'shoe',
    'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=900&q=85',
    array['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=900&q=85'],
    320, 450, 'USD', 89,
    'sneakers', 'unisex',
    null,
    true
  )
on conflict (handle) do update set
  title = excluded.title,
  brand = excluded.brand,
  description = excluded.description,
  department_slug = excluded.department_slug,
  tags = excluded.tags,
  product_type = excluded.product_type,
  home_rails = excluded.home_rails,
  activities = excluded.activities,
  variant_size_preset = excluded.variant_size_preset,
  featured_image_url = excluded.featured_image_url,
  image_gallery = excluded.image_gallery,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  currency = excluded.currency,
  trend_score = excluded.trend_score,
  category = excluded.category,
  gender = excluded.gender,
  source_url = excluded.source_url,
  published = excluded.published,
  updated_at = now();
